# Generated by Django 5.0.1 on 2024-01-05 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batafsil', models.TextField(blank=True, null=True)),
                ('telefon', models.CharField(max_length=13, verbose_name='aloqa uchun telefon')),
                ('yili', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)])),
                ('masofa', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rangi', models.CharField(blank=True, max_length=20, null=True, verbose_name='rangi')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='modeli')),
                ('marka', models.CharField(max_length=30, verbose_name='markasi')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Kami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kami', models.CharField(choices=[('ha', 'Ha'), ('yoq', "Yo'q")], default='ha', max_length=4, verbose_name='Kami bormi ?')),
            ],
        ),
        migrations.CreateModel(
            name='Kuzov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuzov', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchbak'), ('offroad', 'Offroad'), ('universal', 'Universal'), ('kabriolet', 'Kabriolet'), ('krossover', 'Krossover'), ('kupe', 'Kupe'), ('limuzin', 'Limuzin'), ('mikroavtobus', 'Mikroavtobus'), ('miniven', 'Miniven'), ('pikup', 'Pikup'), ('rodster', 'Rodster'), ('furgon', 'Furgon')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ("farg'ona", "Farg'ona"), ('jizzax', 'Jizzax'), ('xorazm', 'Xorazm'), ('namangan', 'Nmanagan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ("qoraqalpog'iston respublikasi", "Qoraqalpog'iston Respublikasi"), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo'), ('toshkent', 'Toshkent')], max_length=30)),
                ('tuman', models.TextField(verbose_name='yashash hududingizni kiriting')),
            ],
        ),
        migrations.CreateModel(
            name='Uzatish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzatish', models.CharField(choices=[('mexanika', 'Mexanika'), ('avtomat', 'Avtomat'), ('tiptronik', 'Tiptronik'), ('variator', 'Variator'), ('robot', 'Robot')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uzatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qutisi', models.CharField(choices=[('oldi', 'Oldi'), ('orqa', 'Orqa'), ("to'liq", "To'liq")], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Yoqilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoqilgi', models.CharField(choices=[('benzin', 'Benzin'), ('gaz-benzin', 'Gaz-Benzin'), ('dizel', 'Dizel'), ('elektr', 'Elektr'), ('gibrid', 'Gibrid'), ('gaz', 'Gaz')], max_length=11)),
            ],
        ),
    ]
