# Generated by Django 5.0.1 on 2024-01-05 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='modeli',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Car_model', to='elon.car_model'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ManyToManyField(related_name='Car_photo', to='elon.image'),
        ),
        migrations.AddField(
            model_name='car',
            name='kami',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Car_kami', to='elon.kami'),
        ),
        migrations.AddField(
            model_name='car',
            name='kuzov',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Car_kuzov', to='elon.kuzov'),
        ),
        migrations.AddField(
            model_name='car',
            name='manzil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Car_location', to='elon.locations'),
        ),
        migrations.AddField(
            model_name='car',
            name='uzatish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Car_qutisi', to='elon.uzatish'),
        ),
        migrations.AddField(
            model_name='car',
            name='uzatma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Car_qutisi', to='elon.uzatma'),
        ),
        migrations.AddField(
            model_name='car',
            name='yoqilgi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Car_yoqilgisi', to='elon.yoqilgi'),
        ),
    ]
