# Generated by Django 5.0.1 on 2024-01-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0003_alter_car_cost_alter_car_kami_alter_car_kuzov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kami',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_kami', to='elon.kami'),
        ),
    ]
