# Generated by Django 5.0.1 on 2024-01-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0004_alter_car_kami'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='kami',
        ),
    ]
