# Generated by Django 5.0.1 on 2024-01-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0005_remove_car_kami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ManyToManyField(related_name='Car_photo', to='elon.image'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='tuman',
            field=models.TextField(blank=True, null=True, verbose_name='yashash hududingizni kiriting'),
        ),
    ]
