# Generated by Django 5.0.1 on 2024-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0006_alter_car_photo_alter_locations_tuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.CharField(default=True, max_length=255, verbose_name='markasi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='modeli',
            field=models.CharField(max_length=255, verbose_name='modeli'),
        ),
    ]
